// Generate frontends/miniapp paletteData.js from engine/palettes/*.json
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const paletteDir = path.join(root, 'engine', 'palettes');
const ids = ['mard_221', 'mard_all', 'universal_24', 'hama_midi', 'perler_standard'];

const palettes = {};
for (const id of ids) {
  // strip UTF-8 BOM if present (engine palette files are saved with BOM)
  const text = fs.readFileSync(path.join(paletteDir, `${id}.json`), 'utf8').replace(/^\uFEFF/, '');
  const raw = JSON.parse(text);
  palettes[id] = {
    brand: raw.brand || 'Unknown',
    version: raw.version || '1.0',
    colors: (raw.colors || []).map((c) => ({
      name: c.name || '',
      code: c.code || '',
      hex: c.hex || '#000000',
    })),
  };
}

const output = `// Auto-generated by scripts/build_miniapp_palette.js — do not edit by hand.
const PALETTES = ${JSON.stringify(palettes, null, 2)};

function getPalette(id) { return PALETTES[id] || PALETTES.universal_24; }
module.exports = { PALETTES, getPalette };
`;

const outPath = path.join(root, 'frontends', 'miniapp', 'pages', 'index', 'paletteData.js');
fs.writeFileSync(outPath, output, 'utf8');
console.log(`Written ${outPath} (${Object.keys(palettes).length} palettes)`);
